services:
  postgres:
    image: postgres:16
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_HOST_AUTH_METHOD: trust
    working_dir: /data
  duckdb:
    image: duckdb
    build:
      context: .
      dockerfile: Dockerfile.duckdb
    volumes:
      - type: bind
        source: ./data
        target: /data
    working_dir: /data
    entrypoint: [ "/bin/bash", "run-experiments-duckdb.sh" ]

  latex:
    image: latex
    build:
      context: .
      dockerfile: Dockerfile.latex
    volumes:
      - type: bind
        source: ./data
        target: /data
