services:
  duckdb:
    image: duckdb
    build:
      context: .
      dockerfile: Dockerfile.duckdb
    volumes:
      - type: bind
        source: .
        target: /project
    working_dir: /project
  postgres:
    image: postgres:16
    volumes:
      - type: bind
        source: .
        target: /project
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_HOST_AUTH_METHOD: trust
    working_dir: /project

volumes:
  postgres_volume:
