services:
  duckdb:
    image: duckdb
    build:
      context: .
      dockerfile: Dockerfile.duckdb
    volumes:
      - type: bind
        source: .
        target: /project
    working_dir: /project
  postgres:
    image: postgres:16
    volumes:
      - type: bind
        source: .
        target: /project
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 80s
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_HOST_AUTH_METHOD: trust
    working_dir: /project
  latex:
    image: danteev/texlive:TL2024-historic
    volumes:
      - type: bind
        source: .
        target: /project
    working_dir: /project

volumes:
  postgres_volume:
