services:
  postgres:
    image: postgres:16
    volumes:
      - type: bind
        source: ./data
        target: /data
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_HOST_AUTH_METHOD: trust
    working_dir: /data
  duckdb:
    image: duckdb
    build:
      context: .
      dockerfile: Dockerfile.duckdb
    volumes:
      - type: bind
        source: ./data
        target: /data
    working_dir: /data
    entrypoint: [ "/bin/bash", "run-experiments-duckdb.sh" ]

volume:
  postgres_volume:
